### ISSUE TITLE
Unify terms

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/internet-draft#20]
Sometimes in the draft, as it currently is, the terms "matcher," "selector," and "filter" seem to be used interchangeably.  These terms need to be explicitly defined, and where we have synonyms, we should only use one.

Personally, I'm in favor of "selector" for everything since JSON Path is technically a query language.  "Matcher", to me, sounds redundant when talking about its action: "A matcher may match a node and, if it matches, ..."  (Section 2.5).  Using the word "selector" here reduces some of the redundancy.

**Comment by glyn** [comment]
Are we looking at the same draft and version? https://jsonpath-standard.github.io/internet-draft/ does not use the term filter, you see.

**Comment by gregsdennis** [comment]
I think I picked up "filter" from [one of my issues](https://github.com/jsonpath-standard/internet-draft/issues/14#issuecomment-697305948).  Still, we should use a single term.

It looks like we've made an effort to define "matcher," but "selector" sounds more appropriate to me.

**Comment by glyn** [comment]
Ok, I'll take a crack at this.

**Comment by remorhaz** [comment]
Filter is a `?(...)` construction. In fact, it's concrete case of a `union-element`.

**Comment by glyn** [comment]
Right, let's ignore filters for this issue. I'll see if we can replace "matcher" with "selector" sensibly.
