### ISSUE TITLE
Define behaviour for very large array indices and slice components

### ISSUE THREAD

**Issue by glyn** [jsonpath-standard/internet-draft#29]
Currently, there is no limit to the integer values which may be specified as array indices or as components (start, end, or step) of an array slice. The spec needs to define what behaviour is acceptable when very large positive or negative values are used.

For example, suppose a value such as 2^65 or -2^65 is used. May the implementation reject that with a (syntax or "find") error, should it clamp the value to the range of a signed 64 bit integer (*) before proceeding, or should this be handled some other way?

*: this may be too onerous for some implementations, but a signed 32 bit limit could conceivably be too draconian.

As @mkmik points out, JSON does not have sparse arrays, so such large values are unlikely to index valid elements. They simply (!) need to be handled in a consistent and helpful way.

This was prompted by a [discussion](https://github.com/jsonpath-standard/jsonpath-reference-implementation/pull/22#issuecomment-705771250) with @gregsdennis.

**Comment by mkmik** [comment]
a notable language that lacks native 64-bit integers is JavaScript:

```
Welcome to Node.js v14.10.1.
Type ".help" for more information.
> x=1024*1024*1024
1073741824
> x*x
1152921504606847000
```
which is `24` off from the correct value which is `1152921504606846976`. This is because in JS numbers are implemented as 64-bit floats. There are ways around it, using BitNumber etc, but implementors need to deal with it and in some cases it might impact the API of the library.

**Comment by gregsdennis** [comment]
For reference, here's how [JSON Schema] (http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.2) puts it.

> JSON Schema is programming language agnostic, and supports the full range of values described in the data model. Be aware, however, that some languages and JSON parsers may not be able to represent in memory the full range of values describable by JSON.

Fairly straightforward, and it relieves implementations from being _required_ to support some features due to limitations put forth by their framework.

**Comment by glyn** [comment]
> For reference, here's how [JSON Schema](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.2) puts it.
> 
> > JSON Schema is programming language agnostic, and supports the full range of values described in the data model. Be aware, however, that some languages and JSON parsers may not be able to represent in memory the full range of values describable by JSON.
> 
> Fairly straightforward, and it relieves implementations from being _required_ to support some features due to limitations put forth by their framework.

It's straightforward, but it's insufficient as it doesn't define any particular behaviour. In our case, I would like to define the behaviour, e.g. to reject a selector containing an overly large index with either a syntax error or an error from "find". 

> 
> I like having this called out in this way out because it also leaves the door open for frameworks that _can_ handle these features. If you clamp the values, then those bignum tests will need to be removed altogether rather than just marked optional. Or worse, they'd need to remain and be marked as "invalid path" (or similar).

**Comment by gregsdennis** [comment]
I'm not sure what "find" is.

I'm happy for the spec to say what the behavior is, but leave the limit up to the implementation.

**Comment by glyn** [comment]
> I'm not sure what "find" is.

I just meant running the selector, rather than parsing it.

> 
> I'm happy for the spec to say what the behavior is, but leave the limit up to the implementation.

Great.

**Comment by glyn** [comment]
I believe this was addressed by PR 31.
